#!/bin/zsh

unset BUNDLE_PATH

tmux new-session -A -D -s primary
tmux list-windows -t primary  | cut -d: -f1|xargs -I{} tmux send-keys -t $session:{} ENTER "export VSCODE_IPC_HOOK_CLI=`ls -tr /tmp/vscode-ipc-* | tail -n 1`" ENTER
return 0
